# Generated by Django 4.2.7 on 2023-11-28 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('about_contract', models.TextField(blank=True, null=True)),
                ('expected_monthly_salary', models.CharField(blank=True, max_length=255, null=True)),
                ('sign_for_contracts', models.ImageField(blank=True, null=True, upload_to='sign/')),
                ('is_activate', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrolls.uservacancy')),
            ],
        ),
        migrations.CreateModel(
            name='CreateInvoiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoice/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrolls.usercontact')),
            ],
        ),
    ]
