# Generated by Django 4.2.7 on 2023-11-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0002_usercontact_createinvoicecontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
