# Generated by Django 4.2.7 on 2023-11-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0003_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='sign_for_contracts',
        ),
    ]
