# Generated by Django 4.2.7 on 2023-11-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0004_remove_usercontact_sign_for_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='is_write',
            field=models.BooleanField(default=False),
        ),
    ]
