# Generated by Django 4.2.7 on 2023-11-28 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrolls', '0005_usercontact_is_write'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrolls.jobcategories')),
            ],
        ),
        migrations.RemoveField(
            model_name='createinvoicecontract',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='uservacancy',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.DeleteModel(
            name='CreateInvoiceContract',
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
        migrations.DeleteModel(
            name='UserVacancy',
        ),
        migrations.AddField(
            model_name='jobapply',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrolls.jobvacancies'),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
