# Generated by Django 4.2.7 on 2023-11-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0007_jobattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancies',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categor_id', to='enrolls.jobcategories'),
        ),
    ]
