# Generated by Django 4.2.7 on 2023-11-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0007_jobattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='is_activate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
