# Generated by Django 4.2.7 on 2023-11-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0008_jobapply_is_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='is_activate',
        ),
        migrations.AddField(
            model_name='jobapply',
            name='jobs_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrolls.statusapply'),
        ),
    ]
