# Generated by Django 4.2.7 on 2023-11-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0009_alter_jobapply_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='enrolls.jobvacancies'),
        ),
    ]
