# Generated by Django 4.2.7 on 2023-11-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0009_statusapply_remove_jobapply_is_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='jobs_status',
            field=models.ForeignKey(blank=True, default='No Chooses', null=True, on_delete=django.db.models.deletion.CASCADE, to='enrolls.statusapply'),
        ),
    ]
