# Generated by Django 4.2.7 on 2023-11-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0010_alter_jobapply_jobs'),
        ('enrolls', '0011_alter_jobapply_jobs_status'),
    ]

    operations = [
    ]
